AY2425S2-CS2103T-F11-4/tp

src/main/java/wanted/commons/core/datatypes/Date.java
src/main/java/wanted/commons/core/datatypes/Index.java
src/main/java/wanted/commons/core/datatypes/MoneyInt.java
src/main/java/wanted/logic/commands/DeleteCommand.java
src/main/java/wanted/logic/commands/EditCommand.java
src/main/java/wanted/logic/parser/DeleteCommandParser.java
src/main/java/wanted/logic/parser/EditCommandParser.java
src/main/java/wanted/logic/parser/ParserUtil.java
src/test/java/wanted/commons/core/datatypes/DateTest.java
src/test/java/wanted/commons/core/datatypes/IndexTest.java
src/test/java/wanted/commons/core/datatypes/MoneyIntTest.java
src/test/java/wanted/logic/commands/CommandTestUtil.java
src/test/java/wanted/logic/commands/DeleteCommandTest.java
src/test/java/wanted/logic/commands/EditCommandTest.java
src/test/java/wanted/logic/parser/EditCommandParserTest.java
src/test/java/wanted/logic/parser/ParserUtilTest.java
src/test/java/wanted/testutil/TestUtil.java
src/test/java/wanted/testutil/TypicalIndexes.java

- Wrote a new data class `MoneyInt` that represents a non-negative number which is a multiple of 1/100
- Wrote a test for it
- Moved all the datatype-related classes (Index, Date, and MoneyInt) into a new package `commons.core.datatypes`
Solves #46

Add MoneyInt class

---

docs/UserGuide.md

Update add documentation

---

src/main/java/wanted/logic/commands/RepayCommand.java
src/main/java/wanted/logic/parser/AddressBookParser.java
src/main/java/wanted/logic/parser/RepayCommandParser.java
src/test/java/wanted/logic/commands/RepayCommandTest.java

Add repay command feature. Still completing testcases.

Add Repay Command

---

src/test/java/wanted/logic/commands/RepayCommandTest.java

Fix checkstyle errors

---

src/main/java/wanted/ui/HelpWindow.java

Change link shown in help window

---

src/main/java/wanted/commons/core/datatypes/MoneyInt.java
src/main/java/wanted/logic/Messages.java
src/main/java/wanted/logic/commands/EditCommand.java
src/main/java/wanted/logic/commands/RepayCommand.java
src/main/java/wanted/logic/parser/AddCommandParser.java
src/main/java/wanted/model/loan/Amount.java
src/main/java/wanted/model/loan/Loan.java
src/main/java/wanted/model/util/SampleDataUtil.java
src/main/java/wanted/storage/JsonAdaptedLoan.java
src/main/java/wanted/ui/LoanCard.java
src/test/data/JsonSerializableLoanBookTest/invalidPersonLoanBook.json
src/test/java/wanted/commons/core/datatypes/MoneyIntTest.java
src/test/java/wanted/logic/commands/RepayCommandTest.java
src/test/java/wanted/logic/parser/AddCommandParserTest.java
src/test/java/wanted/logic/parser/AddressBookParserTest.java
src/test/java/wanted/model/loan/AmountTest.java
src/test/java/wanted/model/loan/LoanTest.java
src/test/java/wanted/storage/JsonAdaptedLoanTest.java
src/test/java/wanted/testutil/EditPersonDescriptorBuilder.java
src/test/java/wanted/testutil/PersonBuilder.java
src/test/java/wanted/testutil/PersonUtil.java

WARNING: Date should be moved from Loan class to the proposed History class. As such, all test cases involving Dates will need to be updated to remove Dates from their use, including Commands.

Restructure loan model

---

src/main/java/wanted/logic/commands/SortCommand.java
src/main/java/wanted/logic/parser/AddressBookParser.java
src/main/java/wanted/logic/parser/SortCommandParser.java
src/test/java/wanted/logic/commands/SortCommandTest.java

Add new command to sort loan via amount value.

Add sort command

---

src/main/java/wanted/logic/commands/IncreaseCommand.java
src/main/java/wanted/logic/parser/AddressBookParser.java
src/main/java/wanted/logic/parser/IncreaseCommandParser.java
src/test/java/wanted/logic/commands/IncreaseCommandTest.java
src/test/java/wanted/logic/parser/AddressBookParserTest.java
src/test/java/wanted/logic/parser/IncreaseCommandTest.java

The opposite of repay. Increase the amount an individual has loaned out. 
Format: "increase [ID] l/[Amount]"
Example: "increase 2 l/10.90"

New increase command

---

README.md
docs/index.md

Fix badges on README.md and index.md

---

src/main/java/wanted/ui/HelpWindow.java
src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml

Make userguide clickable

---

docs/diagrams/ModelClassDiagram.puml

Inherited failed test cases from earlier PRs. No functional code change in this PR.

Update Model UML class diagram

---

src/main/java/wanted/storage/JsonAdaptedLoan.java
src/main/java/wanted/storage/JsonAdaptedLoanTransaction.java
src/test/data/JsonSerializableLoanBookTest/duplicatePersonLoanBook.json
src/test/data/JsonSerializableLoanBookTest/invalidPersonLoanBook.json
src/test/data/JsonSerializableLoanBookTest/typicalPersonsLoanBook.json
src/test/java/wanted/logic/LogicManagerTest.java
src/test/java/wanted/logic/commands/EditLoanDescriptorTest.java
src/test/java/wanted/logic/parser/IncreaseCommandParserTest.java
src/test/java/wanted/storage/JsonAdaptedLoanTest.java
src/test/java/wanted/storage/JsonAdaptedLoanTransactionTest.java
src/test/java/wanted/storage/JsonSerializableLoanBookTest.java
src/test/java/wanted/testutil/TypicalPersons.java

Modified the `JsonAdaptedLoan` model so that the app can correctly save our new loan models.
Also fixed some issues of storage-related unit tests.
Fix #95

Fix storage and storage-related test issues

---

docs/UserGuide.md

Adds in part of the user guide draft.

Start updating user guide

---

src/main/java/wanted/storage/JsonAdaptedLoan.java
src/test/data/JsonLoanBookStorageTest/invalidAndValidPersonLoanBook.json
src/test/data/JsonLoanBookStorageTest/invalidPersonLoanBook.json

Fix jsonproperty

---

src/main/java/wanted/model/util/SampleDataUtil.java

Add transactions in sample data

---

docs/UserGuide.md

Add guide to delete phone number

Update UserGuide.md about phone command

---

src/main/java/wanted/logic/commands/BaseEdit.java
src/main/java/wanted/model/loan/Loan.java
src/main/java/wanted/model/util/SampleDataUtil.java
src/test/java/wanted/logic/commands/DelhistCommandTest.java
src/test/java/wanted/logic/commands/EdithistCommandTest.java
src/test/java/wanted/model/loan/LoanTest.java
src/test/java/wanted/testutil/PersonBuilder.java
src/test/java/wanted/testutil/TypicalPersons.java

Fix #235 
This problem was caused by some commands calling the old constructor of Loan, which does not take Phone as an argument and sets this.phone as the default value.
To ensure that there's no bugs left, I replaced all the usages of the old Loan constructor (including test codes) with the one that requires Phone, and deleted the old constructor.
Total lines of modified functional codes: 22

Fix the vanishing-phone problem

---

docs/UserGuide.md

Fixed some known issues in the quick start and the command summary sections. 
Also involves a few modifications to increase consistency.
Fix #172 Fix #178 Fix #185 Fix #215

Update UG: modify quick start and command summary

---

src/main/java/wanted/ui/LoanCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/LoanListCard.fxml

1) Added label for Total Loaned amount
2) Styled name to be larger

Add total loaned amount and styled name to be larger

---

docs/UserGuide.md

Updating user guide documentation format

---

src/main/java/wanted/logic/commands/RenameCommand.java

Rename message outputs "New name must be different.."

---

docs/UserGuide.md
docs/_markbind/layouts/default.md

Waiting for other PRs on the userguide 
This PR solves some issues from my other merge (sorry) such as incorrect spelling or duplicate commands being recorded. 
Recommended not to merge this but to instead copy over the changes into your PR.

Do not merge: Fix formatting errors

---

docs/UserGuide.md

Update behaviour section of some commands 
Update table of contents

Update behaviour and table of contents
